### ISSUE TITLE
Google Map Api

### ISSUE THREAD

**Issue by skhanzad** [Nahzilian/cps630_final_project#3]
InvalidValueError: not an instance of HTMLInputElement
when leaving from services page.
Uncaught (in promise) 
when going back to services page from other pages

[Temporary Solution]: refresh server on services to use auto complete functionality

**Comment by Nahzilian** [comment]
I figured that it is being called asynchronously, so it is best just to move it right after the initmap script

**Comment by Nahzilian** [comment]
Will be pushed in the next commit
